[package]
name = "bitcoin-rpc-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[[bin]]
name = "bitcoin-rpc-codegen"
path = "src/main.rs"
