[package]
name = "bitcoin-rpc-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
# Optional: specify path if not using the default `src/lib.rs`
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"                                 # Replace with the correct version if known
reqwest = "0.12.15"
jsonrpc_client = "0.7.1"
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.10"
log = "0.4"

[dev-dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde_json = "1"
tempfile = "3.3"
mockall = "0.13.1"

bitcoind = "0.36"
bitcoincore-rpc = "0.19"
bitcoin = "0.32"

[features]
# v28 = [
#     "bitcoincore-rpc/v28",
#     "bitcoind/v28",
# ] # Assuming these are the correct feature flags

[[bin]]
name = "bitcoin-rpc-codegen"
path = "src/src/main.rs"
