[workspace]
members = [
    "core",
    "parser",
    "schema",
    "codegen",
    "transport",
    "client",
    "node",
    "pipeline",
    "cli",
    "config",
    "util",
    "logging",
    "metrics",
    "integration-test",
    "fuzz",
    "verify",
]
