[workspace]
resolver = "2"
members = [
    "rpc_api",
    "parser",
    "schema",
    "codegen",
    "transport",
    "client",
    "node",
    "pipeline",
    "rpc-cli",
    "config",
    "util",
    "logging",
    "rpc_metrics",
    "integration-test",
    "fuzz",
    "verify",
]
