[package]
name = "rpc-api"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# tempfile = "3.5.0"
thiserror = "2.0.12"
