[package]
name = "pipeline"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tracing = "0.1"
config = { path = "../config" }

clap = { version = "4.4", features = ["derive"] }
tracing-subscriber = "0.3"

codegen = { path = "../codegen" }
logging = { path = "../logging" }
parser = { path = "../parser" }
rpc-api = { path = "../rpc-api" }
schema = { path = "../schema" }
transport = { path = "../transport" }
