[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
serde_json = "1.0"
thiserror = "2.0.12"
rpc-api = { path = "../rpc-api" }

[dev-dependencies]
tempfile = "3.8"
