[package]
name = "schema"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
rpc-api = { path = "../rpc-api" }
parser = { path = "../parser" }
thiserror = "2.0.12"
serde_json = "1.0.140"
